#!/bin/bash

MANIFEST=git://github.com/CipherOS/android_manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name techyminati
git config --global user.email sinha.aryan03@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
git clone https://github.com/Xiaomi-SDM439-Development/android_device_xiaomi_olives device/xiaomi/olives
git clone https://github.com/Aghora7/main_tree device/xiaomi/sdm439-common && cd device/xiaomi/sdm439-common && git reset --hard 9f9a9c712694c3b9a1e0ad32372c5e50b3d8d8d4 && cd ../../..

